name: Docker Compose Test Workflow

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Setup Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Build and run tests
    - name: Run tests
      run: |
        docker compose -f tests/docker/docker-compose.tests.yml up --build -V --exit-code-from tests
